apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  labels:
    app: frontend
    tier: web
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Prueba DevOps</title></head>
    <body>
    <h1>Bienvenido a la prueba técnica</h1>
    <p>Servido desde el pod: <strong style="color:red;">{{HOSTNAME}}</strong></p>
    <p>Replica actual: consulta la variable de entorno HOSTNAME.</p>
    </body>
    </html>
